// lib/recipes.ts — lookup recipe from lib/recipes.json (generated by scripts/xlsx2recipes.py)
import recipesData from './recipes.json'

export interface RecipeIngredient {
  label: string
  value: string
}

export interface Recipe {
  note: string | null
  sweet: string
  ingredients: RecipeIngredient[]
  steps: string[]
}

type RecipeEntry = {
  note: string | null
  rows: Record<string, { ingredients: RecipeIngredient[]; instructions: string }>
}

const RECIPES = recipesData as unknown as Record<string, RecipeEntry>

// Excel only has 100/50/None — map any label sweet to the nearest available row.
function mapSweet(sweet: string | null): string {
  if (!sweet) return '100% Sweet'
  if (/none/i.test(sweet)) return 'None Sweet'
  if (/^(50|25)%/.test(sweet)) return '50% Sweet'
  return '100% Sweet' // Regular / 75% / 100% / Extra
}

export function findRecipe(drinkName: string, sweet: string | null): Recipe | null {
  const entry = RECIPES[drinkName]
  if (!entry) return null

  const level = mapSweet(sweet)
  const row = entry.rows[level] ?? Object.values(entry.rows)[0]
  if (!row) return null

  // "Blend on 6 then add Ice and blend on 4" / "blend on 4.  Swirl ..."
  const steps = row.instructions
    .split(/\s+then\s+|\.\s+/i)
    .map((s) => s.trim())
    .filter(Boolean)

  return { note: entry.note, sweet: level, ingredients: row.ingredients, steps }
}
